---
- name: Password Changes - Quarterly Security Activities
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Execute FortiGate - Password Changes (VPN users)
      include_tasks: ../../roles/fortigate/password_changes/tasks/main.yml