---
- name: CHD SAD - Daily Security Activities
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Execute FortiGate - System Events
      include_tasks: ../../roles/fortigate/system_events/tasks/main.yml

    - name: Execute Checkpoint - Events IPS
      include_tasks: ../../roles/checkpoint/events_ips/tasks/main.yml