---
- name: Compromised Passwords - Daily Security Activities
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Execute FortiGate - Admin Login Failed
      include_tasks: ../../roles/fortigate/admin_login_failed/tasks/main.yml

    - name: Execute Checkpoint - Authentication Failures
      include_tasks: "../../roles/checkpoint/authentication failures/tasks/main.yml"
